apiVersion: apps/v1
kind: Deployment
metadata:
  name: journal-backend
  labels:
    app: journal-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: journal-backend
  template:
    metadata:
      labels:
        app: journal-backend
    spec:
      containers:
        - name: backend
          image: us-central1-docker.pkg.dev/project-2dca42d9-9230-4b9e-839/journal-repo/journal-backend:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8081
              name: http
          env:
            - name: DB_HOST
              value: "postgres-0.postgres-service.default.svc.cluster.local"
            - name: DB_PORT
              value: "5432"
            - name: DB_NAME
              value: "journaldb"
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: postgres-user
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: postgres-password
          startupProbe:
            httpGet:
              path: /public/health-check
              port: 8081
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 30 # Up to 300 seconds for initial Dynatrace/DB startup
          livenessProbe:
            httpGet:
              path: /public/health-check
              port: 8081
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /public/health-check
              port: 8081
            periodSeconds: 10
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "500m"
              memory: "1Gi"
---
apiVersion: v1
kind: Service
metadata:
  name: journal-backend-service
  labels:
    app: journal-backend
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
spec:
  type: ClusterIP
  ports:
    - port: 8081
      targetPort: 8081
      protocol: TCP
      name: http
  selector:
    app: journal-backend