apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: journal-ingress
spec:
  ingressClassName: gce # Standard GKE HTTP(S) Load Balancer
  rules:
    - http:
        paths:
          # Backend Spring Boot routes
          - path: /public
            pathType: Prefix
            backend:
              service:
                name: journal-backend-service
                port:
                  number: 8081
          - path: /journal
            pathType: Prefix
            backend:
              service:
                name: journal-backend-service
                port:
                  number: 8081
          - path: /user
            pathType: Prefix
            backend:
              service:
                name: journal-backend-service
                port:
                  number: 8081
          - path: /admin
            pathType: Prefix
            backend:
              service:
                name: journal-backend-service
                port:
                  number: 8081
          # Frontend React routes
          - path: /
            pathType: Prefix
            backend:
              service:
                name: journal-frontend-service
                port:
                  number: 80